
HISTCONTROL=ignoreboth
export MANPAGER=less
# append to the history file, don't overwrite it
shopt -s histappend
shopt -s extglob 
# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe  ] && eval "$(SHELL=/bin/sh lesspipe)"


PS1='\[\033[02;32m\]\u\[\033[1;37m\]@\h\[\033[00m\]:\[\033[01;35m\]\w\[\033[1;39m\]\$\n \A \[\033[1;31m\]> \[\033[00m\] '

alias ls='ls -GlsFh'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias vi='vim'

